version: '2.1'

networks: 
  fabric:
services: 
  org2_ca:
    container_name: org2_ca
    extends: 
      file: ../../docker/base.yaml
      service: ca-base
    networks: 
      - fabric
    ports: 
      - 9054:7054
  org2_peer1:
    container_name: org2_peer1
    extends: 
      file: ../../docker/base.yaml
      service: peer-base
    environment:
        - CORE_PEER_ID=org2_peer1
        - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
        - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
      - ./peer1:/peer
    networks:
      - fabric
    ports: 
      - 9051:7051