version: '2.1'

networks: 
  fabric:
services: 
  org1_ca:
    container_name: org1_ca
    extends: 
      file: ../../docker/base.yaml
      service: ca-base
    networks: 
      - fabric
    ports: 
      - 8054:7054